"""add_cicd_incidents

Revision ID: db3efa7d4d82
Revises: 7e3773979374
Create Date: 2026-06-01 19:57:57.824304
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'db3efa7d4d82'
down_revision: Union[str, None] = '609092d6978f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    # Both types are already created by 7e3773979374 (the `incidents` table's
    # `severity`/`status` columns use plain sa.Enum(...), which auto-creates
    # the Postgres type). These two statements are a defensive no-op on any
    # chain that actually starts from 7e3773979374 -- confirmed live during
    # the Phase 19 migration-drift session (a scratch, empty-DB
    # `alembic upgrade head` run): the `duplicate_object` exception handler
    # silently swallows both, and the real, already-existing type (correct,
    # uppercase 4-value for incidentstatus) is left untouched.
    #
    # The `incidentstatus` value list below was previously lowercase/3-value
    # ('open','investigating','resolved'), which never took effect (it hit
    # the exact same duplicate_object no-op path) but was misleading to read
    # -- corrected here to match the real type's actual, already-existing
    # shape (models/cicd.py's `IncidentStatus`/models/all_models.py's
    # `IncidentStatus`: OPEN/INVESTIGATING/RESOLVED/SUPPRESSED) rather than
    # leaving a value list that looks live but silently isn't.
    op.execute("DO $$ BEGIN CREATE TYPE incidentseverity AS ENUM ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL'); EXCEPTION WHEN duplicate_object THEN null; END $$;")
    op.execute("DO $$ BEGIN CREATE TYPE incidentstatus AS ENUM ('OPEN', 'INVESTIGATING', 'RESOLVED', 'SUPPRESSED'); EXCEPTION WHEN duplicate_object THEN null; END $$;")

    op.create_table('cicd_incidents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('pipeline_id', sa.String(), nullable=False),
    sa.Column('deployment_id', sa.String(), nullable=False),
    sa.Column('severity', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='incidentseverity', create_type=False), nullable=True),
    sa.Column('status', postgresql.ENUM('open', 'investigating', 'resolved', name='incidentstatus', create_type=False), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['deployment_id'], ['pipeline_deployments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cicd_incidents_tenant_id'), 'cicd_incidents', ['tenant_id'], unique=False)
    op.alter_column('pipeline_deployments', 'pipeline_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pipeline_deployments', 'pipeline_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_cicd_incidents_tenant_id'), table_name='cicd_incidents')
    op.drop_table('cicd_incidents')
    # ### end Alembic commands ###
